# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfbbc910a0d9835c5311f94cba78c3714d40b6603ff16d9acb77f3ca1898195777ee1e75934b124bb44378b558e6f6b3b30fe5633843d8af5e50e1000a489e2f

test:
  secret_key_base: 70d9a027fda934853096184e9f251f6f596883fc47d5c8f5d77940601be48b5ff7294ab52542b056c3568af102c415ce27abe0c4cd4099a5b0dd8152720e68ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
